//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacoraPaxFacturacion
    {
        public int idBitacoraFacturacion { get; set; }
        public System.Guid idComprobanteFiscal { get; set; }
        public string mensajeRespuesta { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    
        public virtual facturaComprobanteFiscal facturaComprobanteFiscal { get; set; }
    }
}
