//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracionFacturacionSucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public configuracionFacturacionSucursal()
        {
            this.facturaComprobanteFiscal = new HashSet<facturaComprobanteFiscal>();
        }
    
        public int idConfiguracionFacturacionSucursal { get; set; }
        public string rutaCER { get; set; }
        public string rutaPrivateKey { get; set; }
        public string passwordPrivateKey { get; set; }
        public string serieFactura { get; set; }
        public string usuarioPac { get; set; }
        public string contraseniaPac { get; set; }
        public string emailSender { get; set; }
        public string usuarioSMTP { get; set; }
        public string contraseniaSMTP { get; set; }
        public string serverSMTP { get; set; }
        public int puertoSMTP { get; set; }
        public string rfc { get; set; }
        public string rutaDocumentos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaComprobanteFiscal> facturaComprobanteFiscal { get; set; }
    }
}
