//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturaCompras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facturaCompras()
        {
            this.detalleFacturaCompras = new HashSet<detalleFacturaCompras>();
            this.impuestosTraslados = new HashSet<impuestosTraslados>();
            this.facturaComprobanteFiscal = new HashSet<facturaComprobanteFiscal>();
        }
    
        public int idfacturaCompra { get; set; }
        public string idTicketSucursal { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public decimal subtotal { get; set; }
        public decimal iva { get; set; }
        public decimal descuento { get; set; }
        public decimal total { get; set; }
        public int claveMetodoPago { get; set; }
        public int claveFormaPago { get; set; }
        public int claveTipoComprobante { get; set; }
        public int catEstatusTicketId { get; set; }
        public string referencia { get; set; }
        public string importeLetraTotal { get; set; }
        public string numeroTarjeta { get; set; }
        public string condicionesPago { get; set; }
        public int moneda { get; set; }
        public decimal tipoCambio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleFacturaCompras> detalleFacturaCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<impuestosTraslados> impuestosTraslados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaComprobanteFiscal> facturaComprobanteFiscal { get; set; }
    }
}
