//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionApi.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FacturacionContext : DbContext
    {
        public FacturacionContext()
            : base("name=FacturacionContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bitacoraPaxFacturacion> bitacoraPaxFacturacion { get; set; }
        public virtual DbSet<catEstatusComprobante> catEstatusComprobante { get; set; }
        public virtual DbSet<configuracionFacturacionSucursal> configuracionFacturacionSucursal { get; set; }
        public virtual DbSet<impuestosTraslados> impuestosTraslados { get; set; }
        public virtual DbSet<facturaEmisor> facturaEmisor { get; set; }
        public virtual DbSet<facturaReceptor> facturaReceptor { get; set; }
        public virtual DbSet<detalleFacturaCompras> detalleFacturaCompras { get; set; }
        public virtual DbSet<facturaCompras> facturaCompras { get; set; }
        public virtual DbSet<facturaComprobanteFiscal> facturaComprobanteFiscal { get; set; }
    }
}
