//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturaComprobanteFiscal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facturaComprobanteFiscal()
        {
            this.bitacoraPaxFacturacion = new HashSet<bitacoraPaxFacturacion>();
        }
    
        public System.Guid idfacturaComprobanteFiscal { get; set; }
        public int configuracionFacturacionSucursalId { get; set; }
        public int facturaEmisorId { get; set; }
        public int facturaReceptorId { get; set; }
        public int facturaComprasId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int tipoComprobante { get; set; }
        public string serie { get; set; }
        public string folio { get; set; }
        public Nullable<System.DateTime> fechaCfd { get; set; }
        public string estatus { get; set; }
        public string archivoXmlRuta { get; set; }
        public string archivoPdfruta { get; set; }
        public string cadenaOriginal { get; set; }
        public string documentoTimbrado { get; set; }
        public int catEstatusComprobanteId { get; set; }
        public string lugarExpedicion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bitacoraPaxFacturacion> bitacoraPaxFacturacion { get; set; }
        public virtual catEstatusComprobante catEstatusComprobante { get; set; }
        public virtual configuracionFacturacionSucursal configuracionFacturacionSucursal { get; set; }
        public virtual facturaCompras facturaCompras { get; set; }
        public virtual facturaEmisor facturaEmisor { get; set; }
        public virtual facturaReceptor facturaReceptor { get; set; }
    }
}
