//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturaReceptor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facturaReceptor()
        {
            this.facturaComprobanteFiscal = new HashSet<facturaComprobanteFiscal>();
        }
    
        public int idfacturaReceptor { get; set; }
        public string rfc { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public int cp { get; set; }
        public int catUsoCFDId { get; set; }
        public string direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaComprobanteFiscal> facturaComprobanteFiscal { get; set; }
    }
}
