//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class impuestosTraslados
    {
        public int idImpuestosTraslados { get; set; }
        public decimal tasa { get; set; }
        public int claveImpuesto { get; set; }
        public int idFacturaCompra { get; set; }
        public decimal importe { get; set; }
    
        public virtual facturaCompras facturaCompras { get; set; }
    }
}
