//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionTDCAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraServicio
    {
        public long idBitacoraServicios { get; set; }
        public long tipoServicioId { get; set; }
        public Nullable<long> solicitud { get; set; }
        public string mensajeRespuesta { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    
        public virtual TipoServicio TipoServicio { get; set; }
    }
}
