//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionTDCAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteFiscal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComprobanteFiscal()
        {
            this.BitacoraPaxFacturacions = new HashSet<BitacoraPaxFacturacion>();
        }
    
        public long idComprobanteFiscal { get; set; }
        public int facturaConfiguracionEmisorId { get; set; }
        public long facturaReceptorId { get; set; }
        public long facturaConsumoId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaTimbrado { get; set; }
        public int tipoComprobante { get; set; }
        public string serie { get; set; }
        public string folio { get; set; }
        public string rutaXml { get; set; }
        public string rutaPdf { get; set; }
        public Nullable<System.Guid> uuid { get; set; }
        public string cadenaOriginal { get; set; }
        public string documentoTimbrado { get; set; }
        public int catEstatusComprobanteId { get; set; }
        public System.DateTime fechaCompra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraPaxFacturacion> BitacoraPaxFacturacions { get; set; }
        public virtual CatEstatusComprobante CatEstatusComprobante { get; set; }
        public virtual ReceptorFactura ReceptorFactura { get; set; }
        public virtual ConfiguracionEmisore ConfiguracionEmisore { get; set; }
        public virtual ConsumoFactura ConsumoFactura { get; set; }
    }
}
