//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionTDCAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionEmisore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfiguracionEmisore()
        {
            this.ComprobanteFiscals = new HashSet<ComprobanteFiscal>();
        }
    
        public int idConfiguracionEmisores { get; set; }
        public string rutaCer { get; set; }
        public string rutaPrivateKey { get; set; }
        public string passwordPrivateKey { get; set; }
        public string razonSocial { get; set; }
        public string rfc { get; set; }
        public string direccion { get; set; }
        public int codigoPostal { get; set; }
        public int regimenFiscal { get; set; }
        public string serieFacturas { get; set; }
        public string usuarioPax { get; set; }
        public string contrasenaPax { get; set; }
        public string usuarioSmtp { get; set; }
        public string contrasenaSmtp { get; set; }
        public string serverSmtp { get; set; }
        public string puertoSmtp { get; set; }
        public string rutaDocumentos { get; set; }
        public string descRegimenFiscal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobanteFiscal> ComprobanteFiscals { get; set; }
    }
}
