//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionTDCAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumoFacturaImpuesto
    {
        public long idConsumoFacturaImpuestos { get; set; }
        public long consumoFacturaId { get; set; }
        public decimal tasa { get; set; }
        public int claveImpuesto { get; set; }
        public decimal importe { get; set; }
    
        public virtual ConsumoFactura ConsumoFactura { get; set; }
    }
}
