//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionTDCAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumoFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsumoFactura()
        {
            this.ComprobanteFiscals = new HashSet<ComprobanteFiscal>();
            this.ConsumoFacturaImpuestos = new HashSet<ConsumoFacturaImpuesto>();
            this.ConsumoFacturaDetalles = new HashSet<ConsumoFacturaDetalle>();
        }
    
        public long idConsumoFactura { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public decimal subtotal { get; set; }
        public decimal iva { get; set; }
        public decimal descuento { get; set; }
        public decimal total { get; set; }
        public int claveMetodoPago { get; set; }
        public int claveFormaPago { get; set; }
        public int claveTipoComprobante { get; set; }
        public string referencia { get; set; }
        public string importeLetraTotal { get; set; }
        public string numeroTareta { get; set; }
        public string condicionesPago { get; set; }
        public int moneda { get; set; }
        public decimal tipoCambio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobanteFiscal> ComprobanteFiscals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumoFacturaImpuesto> ConsumoFacturaImpuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumoFacturaDetalle> ConsumoFacturaDetalles { get; set; }
    }
}
