//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionTDCAPI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FacturacionTDCDevEntities : DbContext
    {
        public FacturacionTDCDevEntities()
            : base("name=FacturacionTDCDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BitacoraPaxFacturacion> BitacoraPaxFacturacions { get; set; }
        public virtual DbSet<CatalogoFormaPago> CatalogoFormaPagoes { get; set; }
        public virtual DbSet<CatalogoUsoCfdi> CatalogoUsoCfdis { get; set; }
        public virtual DbSet<CatEstatusComprobante> CatEstatusComprobantes { get; set; }
        public virtual DbSet<ComprobanteFiscal> ComprobanteFiscals { get; set; }
        public virtual DbSet<ConfiguracionEmisore> ConfiguracionEmisores { get; set; }
        public virtual DbSet<ConsumoFactura> ConsumoFacturas { get; set; }
        public virtual DbSet<ConsumoFacturaImpuesto> ConsumoFacturaImpuestos { get; set; }
        public virtual DbSet<ReceptorFactura> ReceptorFacturas { get; set; }
        public virtual DbSet<ReceptorFactura_Legado> ReceptorFactura_Legado { get; set; }
        public virtual DbSet<ConsumoFacturaDetalle> ConsumoFacturaDetalles { get; set; }
        public virtual DbSet<BitacoraServicio> BitacoraServicios { get; set; }
        public virtual DbSet<TipoServicio> TipoServicios { get; set; }
    }
}
