//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionTDCAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptorFactura_Legado
    {
        public int idReceptorFactura_Legado { get; set; }
        public string rfc { get; set; }
        public string razonSocial { get; set; }
        public string correo { get; set; }
        public string codigoPostal { get; set; }
        public int catUsoCfdi { get; set; }
        public string direccion { get; set; }
    }
}
