//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionTDCAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptorFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceptorFactura()
        {
            this.ComprobanteFiscals = new HashSet<ComprobanteFiscal>();
        }
    
        public long idReceptorFactura { get; set; }
        public string rfc { get; set; }
        public string razonSocial { get; set; }
        public string correo { get; set; }
        public string codigoPostal { get; set; }
        public int catUsoCfdi { get; set; }
        public string direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobanteFiscal> ComprobanteFiscals { get; set; }
    }
}
