//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgrupadorInsumos1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgrupadorInsumos1()
        {
            this.ConfiguracionArmadoProductos = new HashSet<ConfiguracionArmadoProductos1>();
            this.InsumoProductos = new HashSet<InsumoProductos1>();
        }
    
        public int idAgrupadorInsumo { get; set; }
        public int comercioId { get; set; }
        public string descripcion { get; set; }
        public bool confirmarPorSeparado { get; set; }
        public int indice { get; set; }
        public Nullable<int> productoId { get; set; }
        public bool agregarExtra { get; set; }
    
        public virtual comercios comercios { get; set; }
        public virtual Productos1 Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfiguracionArmadoProductos1> ConfiguracionArmadoProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsumoProductos1> InsumoProductos { get; set; }
    }
}
