//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnexoDoctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnexoDoctor()
        {
            this.comercios = new HashSet<comercios>();
            this.DoctorAseguranzas = new HashSet<DoctorAseguranzas>();
        }
    
        public int idAnexoDoctor { get; set; }
        public string descripcion { get; set; }
        public string descripcionIngles { get; set; }
        public string cedula { get; set; }
        public int doctorEspecialidadId { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public bool estatus { get; set; }
        public string playerId { get; set; }
        public Nullable<decimal> precioConsulta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comercios> comercios { get; set; }
        public virtual CatDoctorEspecialidad CatDoctorEspecialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorAseguranzas> DoctorAseguranzas { get; set; }
    }
}
