//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public int idArticulo { get; set; }
        public Nullable<int> comercioId { get; set; }
        public string codigoBarra { get; set; }
        public string sku { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> catSubcategoriaId { get; set; }
        public Nullable<int> proveedorId { get; set; }
        public Nullable<int> unidadMedidaId { get; set; }
        public Nullable<int> unidadCompraId { get; set; }
        public Nullable<int> contenidoUnidadCompra { get; set; }
        public Nullable<bool> isAlmacenable { get; set; }
        public Nullable<bool> hasReceta { get; set; }
        public string claveSat { get; set; }
        public Nullable<decimal> costoSinImpuesto { get; set; }
        public Nullable<decimal> costoConImpuesto { get; set; }
        public Nullable<decimal> precioSinImpuesto { get; set; }
        public Nullable<decimal> precioConImpuesto { get; set; }
        public Nullable<decimal> margenUtilidad { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> ieps { get; set; }
        public Nullable<int> estatusId { get; set; }
    
        public virtual Articulos Articulos1 { get; set; }
        public virtual Articulos Articulos2 { get; set; }
    }
}
