//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficioHorarios
    {
        public int beneficioHorarioId { get; set; }
        public int beneficioId { get; set; }
        public Nullable<int> diasNum { get; set; }
        public string horarioInicio { get; set; }
        public string horarioFin { get; set; }
        public string descripcion { get; set; }
    
        public virtual beneficios beneficios { get; set; }
    }
}
