//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public beneficios()
        {
            this.beneficioAplicados = new HashSet<beneficioAplicados>();
            this.beneficioCalificaciones = new HashSet<beneficioCalificaciones>();
            this.beneficioHorarios = new HashSet<beneficioHorarios>();
            this.confBeneficioSucursal = new HashSet<confBeneficioSucursal>();
            this.notificaciones = new HashSet<notificaciones>();
            this.wallet = new HashSet<wallet>();
            this.Descuentos = new HashSet<Descuentos>();
        }
    
        public int idBeneficio { get; set; }
        public int comercioId { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public int usuarioRegistroId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public byte[] imagenDescuento { get; set; }
        public string imagenExt { get; set; }
        public string imagenTitulo { get; set; }
        public bool estatus { get; set; }
        public string fondoColor { get; set; }
        public string terminosCondiciones { get; set; }
        public string titulo { get; set; }
        public Nullable<bool> isCupon { get; set; }
        public Nullable<bool> isPromocion { get; set; }
        public string tipoCodigo { get; set; }
        public Nullable<int> tipoMembresiaId { get; set; }
        public string cadenaCodigo { get; set; }
        public Nullable<int> nivelMembresia { get; set; }
        public string urlImagenCodigo { get; set; }
        public string descripcionIngles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<beneficioAplicados> beneficioAplicados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<beneficioCalificaciones> beneficioCalificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<beneficioHorarios> beneficioHorarios { get; set; }
        public virtual catTipoMembresias catTipoMembresias { get; set; }
        public virtual comercios comercios { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<confBeneficioSucursal> confBeneficioSucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificaciones> notificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wallet> wallet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Descuentos> Descuentos { get; set; }
    }
}
