//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacoraFacturacion
    {
        public int idBitacoraFacturacion { get; set; }
        public System.Guid facturaClienteId { get; set; }
        public int codigoRespuesta { get; set; }
        public string mensajeRespuesta { get; set; }
    
        public virtual facturaCliente facturaCliente { get; set; }
    }
}
