//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class canjePuntos
    {
        public int idCanjePunto { get; set; }
        public int membresiaId { get; set; }
        public int comercioId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int recompensaId { get; set; }
        public int catEstatusCanjePuntoId { get; set; }
        public decimal valorPuntos { get; set; }
        public Nullable<int> sucursalId { get; set; }
        public Nullable<System.DateTime> fechaFinCanje { get; set; }
        public string folioCanje { get; set; }
        public Nullable<System.DateTime> fechaCanje { get; set; }
        public string folioCompraCanje { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
        public Nullable<decimal> montoCompra { get; set; }
    
        public virtual catEstatusCanjePuntos catEstatusCanjePuntos { get; set; }
        public virtual comercios comercios { get; set; }
        public virtual membresias membresias { get; set; }
        public virtual recompensas recompensas { get; set; }
        public virtual sucursales sucursales { get; set; }
    }
}
