//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargaCompras
    {
        public int idCargaCompra { get; set; }
        public int membresiaId { get; set; }
        public int comercioId { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaCompra { get; set; }
        public string folioCompra { get; set; }
        public decimal montoCompra { get; set; }
        public int catEstatusCargaCompraId { get; set; }
        public int sucursalId { get; set; }
        public string codigoCompra { get; set; }
        public decimal puntos { get; set; }
    
        public virtual catEstatusCargaCompras catEstatusCargaCompras { get; set; }
        public virtual comercios comercios { get; set; }
        public virtual membresias membresias { get; set; }
        public virtual sucursales sucursales { get; set; }
    }
}
