//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class catProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catProductos()
        {
            this.confProductoPVEquivalencia = new HashSet<confProductoPVEquivalencia>();
            this.recompensas = new HashSet<recompensas>();
        }
    
        public int idCatProducto { get; set; }
        public int comercioId { get; set; }
        public string descripcion { get; set; }
        public string imagen { get; set; }
        public string nombre { get; set; }
        public int productoId { get; set; }
    
        public virtual comercios comercios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<confProductoPVEquivalencia> confProductoPVEquivalencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recompensas> recompensas { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
