//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class catTipoMembresias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catTipoMembresias()
        {
            this.beneficios = new HashSet<beneficios>();
            this.confSumaPuntos = new HashSet<confSumaPuntos>();
            this.membresias = new HashSet<membresias>();
            this.recompensas = new HashSet<recompensas>();
        }
    
        public int idcatTipoMembresia { get; set; }
        public int empresaId { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int usuarioRegistroId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<int> nivel { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<bool> vigencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<beneficios> beneficios { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<confSumaPuntos> confSumaPuntos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<membresias> membresias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recompensas> recompensas { get; set; }
    }
}
