//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatTipoPagos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatTipoPagos()
        {
            this.TicketPagos = new HashSet<TicketPagos>();
        }
    
        public int idCatTipoPago { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> comercioId { get; set; }
        public bool activo { get; set; }
        public bool cajaBase { get; set; }
        public Nullable<bool> aplicaCxc { get; set; }
    
        public virtual comercios comercios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketPagos> TicketPagos { get; set; }
    }
}
