//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int idCita { get; set; }
        public int sucursalId { get; set; }
        public int clienteId { get; set; }
        public int estatus { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public System.DateTime fechaCita { get; set; }
        public string telefonoContacto { get; set; }
        public System.DateTime fechaUltimaActualizacion { get; set; }
        public string observaciones { get; set; }
        public string playerIdCliente { get; set; }
        public Nullable<bool> IsBeneficioEscaneado { get; set; }
        public string cadenaCodigo { get; set; }
    
        public virtual CatEstatusCita CatEstatusCita { get; set; }
        public virtual clientes clientes { get; set; }
        public virtual sucursales sucursales { get; set; }
    }
}
