//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class clienteNotificaciones
    {
        public int notificacionId { get; set; }
        public int clienteId { get; set; }
        public int empresaId { get; set; }
        public System.DateTime fechaEnviado { get; set; }
        public bool revisado { get; set; }
        public Nullable<System.DateTime> rechaRevisado { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual notificaciones notificaciones { get; set; }
    }
}
