//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientespv1
    {
        public int idClientespv { get; set; }
        public string nombre { get; set; }
        public string direccionEntrega { get; set; }
        public string telefono { get; set; }
        public Nullable<int> coloniaid { get; set; }
        public bool otraColonia { get; set; }
        public int sucursalId { get; set; }
    }
}
