//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class comentarios
    {
        public int idComentario { get; set; }
        public string mensaje { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<bool> fromComercio { get; set; }
        public Nullable<bool> fromCliente { get; set; }
        public int catTipoComentarioId { get; set; }
        public int clienteId { get; set; }
        public bool activo { get; set; }
        public bool importante { get; set; }
        public bool leido { get; set; }
    
        public virtual catTipoComentario catTipoComentario { get; set; }
        public virtual clientes clientes { get; set; }
    }
}
