//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class comercios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comercios()
        {
            this.beneficios = new HashSet<beneficios>();
            this.canjePuntos = new HashSet<canjePuntos>();
            this.cargaCompras = new HashSet<cargaCompras>();
            this.movimientoPuntos = new HashSet<movimientoPuntos>();
            this.saldoPuntos = new HashSet<saldoPuntos>();
            this.AgrupadorInsumos = new HashSet<AgrupadorInsumos>();
            this.AreaPreparacion = new HashSet<AreaPreparacion>();
            this.CategoriaIngrediente = new HashSet<CategoriaIngrediente>();
            this.CategoriaInsumo = new HashSet<CategoriaInsumo>();
            this.CatEstatusEquipo = new HashSet<CatEstatusEquipo>();
            this.CatEstatusOrden = new HashSet<CatEstatusOrden>();
            this.CatMovimientoInventarios = new HashSet<CatMovimientoInventarios>();
            this.CatTipoEquipo = new HashSet<CatTipoEquipo>();
            this.CatTipoMantenimiento = new HashSet<CatTipoMantenimiento>();
            this.CatTipoPagos = new HashSet<CatTipoPagos>();
            this.ConteoFisicoAgrupadorInsumos = new HashSet<ConteoFisicoAgrupadorInsumos>();
            this.Proveedores = new HashSet<Proveedores>();
            this.TipoRecetas = new HashSet<TipoRecetas>();
            this.UnidadMedida = new HashSet<UnidadMedida>();
            this.datosFiscales = new HashSet<datosFiscales>();
            this.CatRubrosGastos = new HashSet<CatRubrosGastos>();
            this.Insumos = new HashSet<Insumos>();
            this.confUsuarioComercio = new HashSet<confUsuarioComercio>();
            this.catProductos = new HashSet<catProductos>();
            this.ImagenDoctor = new HashSet<ImagenDoctor>();
            this.sucursales = new HashSet<sucursales>();
            this.CatGastos = new HashSet<CatGastos>();
            this.CatCategoriaArticulos = new HashSet<CatCategoriaArticulos>();
            this.CatConceptosGastos = new HashSet<CatConceptosGastos>();
            this.Descuentos = new HashSet<Descuentos>();
            this.CatRubros = new HashSet<CatRubros>();
            this.CategoriaProductos = new HashSet<CategoriaProductos>();
            this.Productos = new HashSet<Productos>();
            this.ConfUsuariosComercioSucursal = new HashSet<ConfUsuariosComercioSucursal>();
        }
    
        public int idComercio { get; set; }
        public int empresaId { get; set; }
        public string nombreComercial { get; set; }
        public Nullable<int> catComercioGiroId { get; set; }
        public string rfc { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string paginaWeb { get; set; }
        public string logoUrl { get; set; }
        public bool estatus { get; set; }
        public int usuarioRegistroId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public string direccion { get; set; }
        public Nullable<int> catTipoComercioId { get; set; }
        public Nullable<int> anexoDoctorId { get; set; }
        public Nullable<bool> puntoVenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<beneficios> beneficios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<canjePuntos> canjePuntos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cargaCompras> cargaCompras { get; set; }
        public virtual catComercioGiros catComercioGiros { get; set; }
        public virtual catTipoComercios catTipoComercios { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientoPuntos> movimientoPuntos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saldoPuntos> saldoPuntos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgrupadorInsumos> AgrupadorInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaPreparacion> AreaPreparacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriaIngrediente> CategoriaIngrediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriaInsumo> CategoriaInsumo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatEstatusEquipo> CatEstatusEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatEstatusOrden> CatEstatusOrden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatMovimientoInventarios> CatMovimientoInventarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTipoEquipo> CatTipoEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTipoMantenimiento> CatTipoMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTipoPagos> CatTipoPagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConteoFisicoAgrupadorInsumos> ConteoFisicoAgrupadorInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proveedores> Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoRecetas> TipoRecetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnidadMedida> UnidadMedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datosFiscales> datosFiscales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatRubrosGastos> CatRubrosGastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insumos> Insumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<confUsuarioComercio> confUsuarioComercio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catProductos> catProductos { get; set; }
        public virtual AnexoDoctor AnexoDoctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenDoctor> ImagenDoctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sucursales> sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatGastos> CatGastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatCategoriaArticulos> CatCategoriaArticulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatConceptosGastos> CatConceptosGastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Descuentos> Descuentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatRubros> CatRubros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriaProductos> CategoriaProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos> Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfUsuariosComercioSucursal> ConfUsuariosComercioSucursal { get; set; }
    }
}
