//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compras()
        {
            this.DetalleCompra = new HashSet<DetalleCompra>();
            this.DetalleCompraReapertura = new HashSet<DetalleCompraReapertura>();
        }
    
        public int idCompra { get; set; }
        public int proveedorId { get; set; }
        public int sucursalId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int usuarioRegistroId { get; set; }
        public string observaciones { get; set; }
        public string noRemision { get; set; }
        public string noFactura { get; set; }
        public decimal descuento { get; set; }
        public decimal iva { get; set; }
        public decimal total { get; set; }
        public bool activo { get; set; }
        public int estatusCompraId { get; set; }
        public Nullable<System.DateTime> fechaCompra { get; set; }
    
        public virtual CatEstatusCompras CatEstatusCompras { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual sucursales sucursales { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompraReapertura> DetalleCompraReapertura { get; set; }
    }
}
