//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class confUsuarioComercio
    {
        public int usuarioId { get; set; }
        public int comercioId { get; set; }
        public Nullable<bool> permiso { get; set; }
        public bool verReportes { get; set; }
        public bool verSoporte { get; set; }
        public bool verComentarios { get; set; }
        public bool verNotificaciones { get; set; }
        public bool verComercioAfiliado { get; set; }
        public bool verArqueo { get; set; }
        public bool verFacturas { get; set; }
        public bool verUsuarios { get; set; }
        public bool verCatalogos { get; set; }
    
        public virtual comercios comercios { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
