//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class confProductoPVEquivalencia
    {
        public int idConfProductoPVEquivalencia { get; set; }
        public int catProductoId { get; set; }
        public int productoPuntoVentaId { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual catProductos catProductos { get; set; }
    }
}
