//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfSucursales
    {
        public int idConfSucursal { get; set; }
        public int sucursalId { get; set; }
        public decimal montoMinimo { get; set; }
        public decimal costoEnvio { get; set; }
        public bool activoPlataforma { get; set; }
        public Nullable<bool> tieneDriveThru { get; set; }
    
        public virtual sucursales sucursales { get; set; }
    }
}
