//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfMenuPlatillosItemDos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfMenuPlatillosItemDos()
        {
            this.ConfMenuPlatillosItemTres = new HashSet<ConfMenuPlatillosItemTres>();
        }
    
        public int idConfMenuPlatillosItemDos { get; set; }
        public int confMenuPlatillosItemUnoId { get; set; }
        public Nullable<int> itemDosId { get; set; }
        public decimal precio { get; set; }
        public int cantidadSeleccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfMenuPlatillosItemTres> ConfMenuPlatillosItemTres { get; set; }
        public virtual ItemDos ItemDos { get; set; }
        public virtual ConfMenuPlatillosItemUno ConfMenuPlatillosItemUno { get; set; }
    }
}
