//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfMenuPlatillosItemUno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfMenuPlatillosItemUno()
        {
            this.ConfMenuPlatillosItemDos = new HashSet<ConfMenuPlatillosItemDos>();
        }
    
        public int idConfMenuPlatillosItemUno { get; set; }
        public int menuId { get; set; }
        public int platilloId { get; set; }
        public Nullable<int> itemUnoId { get; set; }
        public decimal precio { get; set; }
        public int cantidadSeleccion { get; set; }
        public Nullable<int> SucursalID { get; set; }
    
        public virtual CategoriaProductos CategoriaProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfMenuPlatillosItemDos> ConfMenuPlatillosItemDos { get; set; }
        public virtual ItemUno ItemUno { get; set; }
        public virtual sucursales sucursales { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual CategoriaProductos1 CategoriaProductos1 { get; set; }
        public virtual Productos1 Productos1 { get; set; }
    }
}
