//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracionSistema
    {
        public int configuracionSistemaId { get; set; }
        public Nullable<int> empresaId { get; set; }
        public Nullable<int> diasFechasFiltros { get; set; }
        public string txtVincularMembresiaApp { get; set; }
        public string urlTerminosCondiciones { get; set; }
        public string telefonoContacto { get; set; }
        public string correoContacto { get; set; }
        public string txtSolicitarBeneficioAbajo { get; set; }
        public string txtTerminosCondiciones { get; set; }
        public string txtSoporte { get; set; }
        public Nullable<int> costoMembresia { get; set; }
        public string conektaPublicKey { get; set; }
        public string conektaPrivateKey { get; set; }
        public string conektaApiVersion { get; set; }
        public Nullable<System.DateTime> fechaInicioMembresia { get; set; }
        public Nullable<System.DateTime> fechaFinMembresia { get; set; }
        public string ftpPerfil { get; set; }
        public string ftpUser { get; set; }
        public string ftpPassword { get; set; }
        public string versionAndroid { get; set; }
        public string versionAndroidTest { get; set; }
        public string versioniOS { get; set; }
        public string versioniOSTest { get; set; }
        public string vrlPublicacion { get; set; }
        public Nullable<bool> dedicadoAComercio { get; set; }
        public Nullable<bool> tienePaginaVinculacion { get; set; }
        public Nullable<bool> tienePaginaConekta { get; set; }
        public Nullable<bool> tienePaginaPuntos { get; set; }
        public string modoTiempo { get; set; }
        public string tiempoProgramado { get; set; }
        public Nullable<int> tiempoIntervalo { get; set; }
        public Nullable<int> intervaloZonaCS { get; set; }
        public string tituloCompartir { get; set; }
        public string contenidoCompartir { get; set; }
        public Nullable<int> idQDC { get; set; }
        public Nullable<bool> mostrarComercios { get; set; }
        public Nullable<bool> mostrarSucursales { get; set; }
        public string soporteLinea1Ingles { get; set; }
        public string soporteLinea2Ingles { get; set; }
    
        public virtual empresas empresas { get; set; }
    }
}
