//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfEnsaladaPlatillos
    {
        public int idConfEnsaladaPlatillo { get; set; }
        public int menuId { get; set; }
        public int platilloId { get; set; }
        public string tamanio { get; set; }
        public decimal precioBase { get; set; }
        public int proteina { get; set; }
        public int barraFria { get; set; }
        public int aderezo { get; set; }
        public int complemento { get; set; }
        public int cortesia { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
