//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumoEmpleados
    {
        public int idConsumoEmpleado { get; set; }
        public int pedidoId { get; set; }
        public string usuarioConsume { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
    }
}
