//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumidoresConekta
    {
        public int idConsumidoresConekta { get; set; }
        public int consumidorId { get; set; }
        public string customerId { get; set; }
        public string tokenId { get; set; }
        public string ultimosDigitos { get; set; }
        public string brand { get; set; }
        public bool activo { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
