//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConteoFisicoAgrupadorInsumos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConteoFisicoAgrupadorInsumos()
        {
            this.ConteoFisicoInsumos = new HashSet<ConteoFisicoInsumos>();
            this.RegistroConteoFisicoInsumos = new HashSet<RegistroConteoFisicoInsumos>();
        }
    
        public int idConteoFisicoAgrupadorInsumos { get; set; }
        public int comercioId { get; set; }
        public string descripcion { get; set; }
        public int conteoFisicoPeriodoCapturaId { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public int unidadMedidaIdConteo { get; set; }
        public int diaConteo { get; set; }
        public int insumoId { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConteoFisicoInsumos> ConteoFisicoInsumos { get; set; }
        public virtual comercios comercios { get; set; }
        public virtual ConteoFisicoPeriodoCaptura ConteoFisicoPeriodoCaptura { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroConteoFisicoInsumos> RegistroConteoFisicoInsumos { get; set; }
        public virtual Insumos Insumos { get; set; }
    }
}
