//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosFiscales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public datosFiscales()
        {
            this.confDatosFiscalesSucursal = new HashSet<confDatosFiscalesSucursal>();
            this.facturaCliente = new HashSet<facturaCliente>();
            this.facturaPendiente = new HashSet<facturaPendiente>();
            this.sucursales = new HashSet<sucursales>();
        }
    
        public int idDatoFiscal { get; set; }
        public Nullable<int> comercioId { get; set; }
        public string nombreFiscal { get; set; }
        public string rfc { get; set; }
        public Nullable<int> direccionId { get; set; }
        public string serieFactura { get; set; }
        public Nullable<int> usuarioRegistroId { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public string cp { get; set; }
        public Nullable<int> catRegimenFiscalId { get; set; }
    
        public virtual catRegimenFiscal catRegimenFiscal { get; set; }
        public virtual comercios comercios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<confDatosFiscalesSucursal> confDatosFiscalesSucursal { get; set; }
        public virtual direccion direccion { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaCliente> facturaCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaPendiente> facturaPendiente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sucursales> sucursales { get; set; }
    }
}
