//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedidos
    {
        public int IdDetallePedido { get; set; }
        public int pedidoId { get; set; }
        public int platilloId { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precioUnitario { get; set; }
        public string descripcion { get; set; }
        public string nota { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Pedidos1 Pedidos1 { get; set; }
        public virtual Pedidos11 Pedidos11 { get; set; }
        public virtual Productos1 Productos1 { get; set; }
    }
}
