//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRecetaProducto1
    {
        public int recetaId { get; set; }
        public int insumoId { get; set; }
        public int unidadMedidaId { get; set; }
        public decimal cantidad { get; set; }
    
        public virtual Insumos1 Insumos { get; set; }
        public virtual Recetas1 Recetas { get; set; }
        public virtual UnidadMedida1 UnidadMedida { get; set; }
    }
}
