//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompraReapertura1
    {
        public int idDetalleCompraReapertura { get; set; }
        public int compraId { get; set; }
        public int insumoId { get; set; }
        public decimal cantidad { get; set; }
        public Nullable<decimal> precioUnitario { get; set; }
        public decimal importe { get; set; }
        public Nullable<int> unidadCompraId { get; set; }
        public bool procesado { get; set; }
    
        public virtual Compras1 Compras { get; set; }
    }
}
