//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleCompra1()
        {
            this.MovimientoInventarios = new HashSet<MovimientoInventarios1>();
        }
    
        public int idDetalleCompra { get; set; }
        public int compraId { get; set; }
        public int insumoId { get; set; }
        public decimal cantidad { get; set; }
        public Nullable<decimal> precioUnitario { get; set; }
        public decimal importe { get; set; }
        public Nullable<int> unidadCompraId { get; set; }
    
        public virtual Compras1 Compras { get; set; }
        public virtual Insumos1 Insumos { get; set; }
        public virtual UnidadMedida1 UnidadMedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoInventarios1> MovimientoInventarios { get; set; }
    }
}
