//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public direccion()
        {
            this.datosFiscales = new HashSet<datosFiscales>();
            this.empresaKardex = new HashSet<empresaKardex>();
            this.representateLegal = new HashSet<representateLegal>();
            this.sucursales = new HashSet<sucursales>();
        }
    
        public int idDireccion { get; set; }
        public string calle { get; set; }
        public string colonia { get; set; }
        public string numExterior { get; set; }
        public string numInterior { get; set; }
        public string codigoPostal { get; set; }
        public Nullable<int> catCiudadId { get; set; }
        public Nullable<int> catEstadoId { get; set; }
        public string entreCalles { get; set; }
    
        public virtual catCiudades catCiudades { get; set; }
        public virtual catEstados catEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datosFiscales> datosFiscales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empresaKardex> empresaKardex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<representateLegal> representateLegal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sucursales> sucursales { get; set; }
    }
}
