//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorAseguranzas
    {
        public int idDoctorAseguranzas { get; set; }
        public int anexoDoctorId { get; set; }
        public int catAseguranzaId { get; set; }
    
        public virtual AnexoDoctor AnexoDoctor { get; set; }
        public virtual CatAseguranzas CatAseguranzas { get; set; }
    }
}
