//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresaContactos
    {
        public int idEmpresaContactos { get; set; }
        public Nullable<int> empresaId { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string puesto { get; set; }
        public bool estatus { get; set; }
    
        public virtual empresas empresas { get; set; }
    }
}
