//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturaPendiente
    {
        public int idFacturaPendiente { get; set; }
        public string ticket { get; set; }
        public int receptorClienteId { get; set; }
        public int datoFiscalId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public bool pendiente { get; set; }
        public int sucursalId { get; set; }
    
        public virtual datosFiscales datosFiscales { get; set; }
        public virtual receptorCliente receptorCliente { get; set; }
        public virtual sucursales sucursales { get; set; }
    }
}
