//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturaCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facturaCliente()
        {
            this.bitacoraFacturacion = new HashSet<bitacoraFacturacion>();
        }
    
        public System.Guid idFacturaClienteId { get; set; }
        public string ticketSucursalId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int receptorClienteId { get; set; }
        public int datoFiscalId { get; set; }
        public string numeroFactura { get; set; }
        public int catEstatusFacturaId { get; set; }
        public string archivoPdfRuta { get; set; }
        public string archivoXmlRuta { get; set; }
        public string observacion { get; set; }
        public string cadenaOriginal { get; set; }
        public string documentoTimbrado { get; set; }
        public Nullable<System.Guid> originalFacturacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bitacoraFacturacion> bitacoraFacturacion { get; set; }
        public virtual catEstatusFactura catEstatusFactura { get; set; }
        public virtual datosFiscales datosFiscales { get; set; }
        public virtual receptorCliente receptorCliente { get; set; }
        public virtual ticketSucursal ticketSucursal { get; set; }
    }
}
