//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gastos1
    {
        public int idGasto { get; set; }
        public int sucursalId { get; set; }
        public int catConceptoGastoId { get; set; }
        public Nullable<int> proveedorId { get; set; }
        public Nullable<int> GastoPvId { get; set; }
        public string noRemision { get; set; }
        public string noFactura { get; set; }
        public decimal monto { get; set; }
        public string obervacion { get; set; }
        public System.DateTime fechaGasto { get; set; }
        public int usuarioRegistroId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    
        public virtual CatConceptosGastos1 CatConceptosGastos { get; set; }
        public virtual GastosPv1 GastosPv { get; set; }
        public virtual Proveedores1 Proveedores { get; set; }
        public virtual sucursales sucursales { get; set; }
    }
}
