//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosPvDetalle1
    {
        public int idGastoPvDetalle { get; set; }
        public int gastoPvId { get; set; }
        public int sucursalId { get; set; }
        public Nullable<int> proveedorId { get; set; }
        public int catConceptoGastoId { get; set; }
        public Nullable<int> insumoId { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public decimal monto { get; set; }
        public int usuarioRegistroId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<int> gastosId { get; set; }
        public Nullable<int> detalleCompraId { get; set; }
    
        public virtual CatConceptosGastos1 CatConceptosGastos { get; set; }
        public virtual GastosPv1 GastosPv { get; set; }
        public virtual Insumos1 Insumos { get; set; }
        public virtual Proveedores1 Proveedores { get; set; }
        public virtual sucursales sucursales { get; set; }
    }
}
