//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosPv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GastosPv()
        {
            this.Gastos = new HashSet<Gastos>();
            this.GastosPvDetalle = new HashSet<GastosPvDetalle>();
        }
    
        public int idGastoPv { get; set; }
        public int gastoIdSucursal { get; set; }
        public int aperturaId { get; set; }
        public string usuarioRegistro { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public string observaciones { get; set; }
        public string tipoGasto { get; set; }
        public bool aplicado { get; set; }
    
        public virtual Aperturas Aperturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gastos> Gastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastosPvDetalle> GastosPvDetalle { get; set; }
    }
}
