//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insumos()
        {
            this.ConteoFisicoAgrupadorInsumos = new HashSet<ConteoFisicoAgrupadorInsumos>();
            this.ConteoFisicoInsumos = new HashSet<ConteoFisicoInsumos>();
            this.DetalleCompra = new HashSet<DetalleCompra>();
            this.DetalleRecetaProcesados = new HashSet<DetalleRecetaProcesados>();
            this.DetalleRecetaProducto = new HashSet<DetalleRecetaProducto>();
            this.Equivalencias = new HashSet<Equivalencias>();
            this.InsumoProductos = new HashSet<InsumoProductos>();
            this.GastosPvDetalle = new HashSet<GastosPvDetalle>();
            this.Inventarios = new HashSet<Inventarios>();
            this.MovimientoInventarios = new HashSet<MovimientoInventarios>();
            this.RecetasProcesados = new HashSet<RecetasProcesados>();
        }
    
        public int idInsumo { get; set; }
        public int comercioId { get; set; }
        public string nombre { get; set; }
        public Nullable<int> categoriaInsumoId { get; set; }
        public bool esProcesado { get; set; }
        public bool activo { get; set; }
        public int usuarioRegistroId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int unidadMedidaIdMinima { get; set; }
        public int unidadMedidaIdCompra { get; set; }
        public Nullable<int> categoriaIngredienteId { get; set; }
        public bool esIngrediente { get; set; }
        public Nullable<decimal> mermaPermitida { get; set; }
        public string imagen { get; set; }
        public Nullable<bool> aplicaInventario { get; set; }
        public Nullable<int> catRubroId { get; set; }
        public bool conteoFisico { get; set; }
        public Nullable<decimal> equivalencia { get; set; }
        public bool esAgrupador { get; set; }
    
        public virtual CategoriaIngrediente CategoriaIngrediente { get; set; }
        public virtual CategoriaInsumo CategoriaInsumo { get; set; }
        public virtual CatRubros CatRubros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConteoFisicoAgrupadorInsumos> ConteoFisicoAgrupadorInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConteoFisicoInsumos> ConteoFisicoInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRecetaProcesados> DetalleRecetaProcesados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRecetaProducto> DetalleRecetaProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equivalencias> Equivalencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsumoProductos> InsumoProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastosPvDetalle> GastosPvDetalle { get; set; }
        public virtual comercios comercios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventarios> Inventarios { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        public virtual UnidadMedida UnidadMedida1 { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoInventarios> MovimientoInventarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetasProcesados> RecetasProcesados { get; set; }
    }
}
