//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumos1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insumos1()
        {
            this.ConteoFisicoAgrupadorInsumos = new HashSet<ConteoFisicoAgrupadorInsumos1>();
            this.ConteoFisicoInsumos = new HashSet<ConteoFisicoInsumos1>();
            this.DetalleCompra = new HashSet<DetalleCompra1>();
            this.DetalleRecetaProcesados = new HashSet<DetalleRecetaProcesados1>();
            this.DetalleRecetaProducto = new HashSet<DetalleRecetaProducto1>();
            this.Equivalencias = new HashSet<Equivalencias1>();
            this.GastosPvDetalle = new HashSet<GastosPvDetalle1>();
            this.InsumoProductos = new HashSet<InsumoProductos1>();
            this.Inventarios = new HashSet<Inventarios1>();
            this.MovimientoInventarios = new HashSet<MovimientoInventarios1>();
            this.RecetasProcesados = new HashSet<RecetasProcesados1>();
        }
    
        public int idInsumo { get; set; }
        public int comercioId { get; set; }
        public string nombre { get; set; }
        public Nullable<int> categoriaInsumoId { get; set; }
        public bool esProcesado { get; set; }
        public bool activo { get; set; }
        public int usuarioRegistroId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int unidadMedidaIdMinima { get; set; }
        public int unidadMedidaIdCompra { get; set; }
        public Nullable<int> categoriaIngredienteId { get; set; }
        public bool esIngrediente { get; set; }
        public Nullable<decimal> mermaPermitida { get; set; }
        public string imagen { get; set; }
        public Nullable<bool> aplicaInventario { get; set; }
        public Nullable<int> catRubroId { get; set; }
        public bool conteoFisico { get; set; }
        public Nullable<decimal> equivalencia { get; set; }
        public bool esAgrupador { get; set; }
    
        public virtual CategoriaIngrediente1 CategoriaIngrediente { get; set; }
        public virtual CategoriaInsumo1 CategoriaInsumo { get; set; }
        public virtual CatRubros1 CatRubros { get; set; }
        public virtual comercios comercios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConteoFisicoAgrupadorInsumos1> ConteoFisicoAgrupadorInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConteoFisicoInsumos1> ConteoFisicoInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra1> DetalleCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRecetaProcesados1> DetalleRecetaProcesados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRecetaProducto1> DetalleRecetaProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equivalencias1> Equivalencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastosPvDetalle1> GastosPvDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsumoProductos1> InsumoProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventarios1> Inventarios { get; set; }
        public virtual UnidadMedida1 UnidadMedida { get; set; }
        public virtual UnidadMedida1 UnidadMedida1 { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoInventarios1> MovimientoInventarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetasProcesados1> RecetasProcesados { get; set; }
    }
}
