//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventarios1
    {
        public int idInventario { get; set; }
        public int insumoId { get; set; }
        public int sucursalId { get; set; }
        public bool activo { get; set; }
        public decimal precio { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public decimal maximo { get; set; }
        public decimal minimo { get; set; }
        public decimal cantidad { get; set; }
    
        public virtual Insumos1 Insumos { get; set; }
        public virtual sucursales sucursales { get; set; }
    }
}
