//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoMobiliarioEquipos
    {
        public int idMantenimientoMobiliarioEquipo { get; set; }
        public int mobiliarioEquipoId { get; set; }
        public int catTipoMantenimientoId { get; set; }
        public bool isDlls { get; set; }
        public decimal importe { get; set; }
        public string descripcion { get; set; }
        public int usuarioRegistroId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public System.DateTime fechaMantenimiento { get; set; }
        public Nullable<System.DateTime> proximaFechaMantenimiento { get; set; }
        public string urlDocumento { get; set; }
    
        public virtual CatTipoMantenimiento CatTipoMantenimiento { get; set; }
        public virtual MobiliarioEquipos MobiliarioEquipos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
