//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class membresias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public membresias()
        {
            this.beneficioAplicados = new HashSet<beneficioAplicados>();
            this.canjePuntos = new HashSet<canjePuntos>();
            this.cargaCompras = new HashSet<cargaCompras>();
            this.movimientoPuntos = new HashSet<movimientoPuntos>();
            this.saldoPuntos = new HashSet<saldoPuntos>();
        }
    
        public int idMembresia { get; set; }
        public int catTipoMembresiaId { get; set; }
        public int clienteId { get; set; }
        public string folio { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public bool estatus { get; set; }
        public string guid { get; set; }
        public Nullable<System.DateTime> fechaVinculo { get; set; }
        public Nullable<bool> isCompraDigital { get; set; }
        public Nullable<decimal> costo { get; set; }
        public string codigoQR { get; set; }
        public string codigoBarra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<beneficioAplicados> beneficioAplicados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<canjePuntos> canjePuntos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cargaCompras> cargaCompras { get; set; }
        public virtual catTipoMembresias catTipoMembresias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientoPuntos> movimientoPuntos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saldoPuntos> saldoPuntos { get; set; }
        public virtual clientes clientes { get; set; }
    }
}
