//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobiliarioEquipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MobiliarioEquipos()
        {
            this.MantenimientoMobiliarioEquipos = new HashSet<MantenimientoMobiliarioEquipos>();
        }
    
        public int idMobiliarioEquipo { get; set; }
        public int sucursalId { get; set; }
        public string claveEquipo { get; set; }
        public int catTipoEquipoId { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string serie { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public int catEstatusEquipoId { get; set; }
        public int usuarioRegistroId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<int> usuarioActualizoId { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
    
        public virtual CatEstatusEquipo CatEstatusEquipo { get; set; }
        public virtual CatTipoEquipo CatTipoEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoMobiliarioEquipos> MantenimientoMobiliarioEquipos { get; set; }
        public virtual sucursales sucursales { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
    }
}
