//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoInventarios
    {
        public int idMovimientoInventario { get; set; }
        public Nullable<int> catMovimientoId { get; set; }
        public int insumoId { get; set; }
        public int sucursalId { get; set; }
        public decimal cantidad { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<int> usuarioRegistroId { get; set; }
        public Nullable<int> detalleCompraId { get; set; }
        public string tipoMovimiento { get; set; }
        public Nullable<int> aperturaId { get; set; }
        public Nullable<int> unidadMedidaCompraId { get; set; }
        public string unidadMedidaCompraDesc { get; set; }
        public Nullable<int> unidadMedidaConsumoId { get; set; }
        public string unidadMedidaConsumoaDesc { get; set; }
        public string observaciones { get; set; }
        public Nullable<decimal> cantidadConsumo { get; set; }
    
        public virtual CatMovimientoInventarios CatMovimientoInventarios { get; set; }
        public virtual DetalleCompra DetalleCompra { get; set; }
        public virtual Insumos Insumos { get; set; }
        public virtual sucursales sucursales { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
