//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacionesHazPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotificacionesHazPedido()
        {
            this.ConsumidorNotificaciones = new HashSet<ConsumidorNotificaciones>();
        }
    
        public int idNotificacionHazPedido { get; set; }
        public Nullable<int> sucursalId { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int usuarioRegistro { get; set; }
        public Nullable<int> pedidoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumidorNotificaciones> ConsumidorNotificaciones { get; set; }
        public virtual sucursales sucursales { get; set; }
        public virtual Pedidos1 Pedidos1 { get; set; }
        public virtual Pedidos11 Pedidos11 { get; set; }
    }
}
