//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public notificaciones()
        {
            this.clienteNotificaciones = new HashSet<clienteNotificaciones>();
            this.SectoresNotificaciones = new HashSet<SectoresNotificaciones>();
            this.SucursalNotificaciones = new HashSet<SucursalNotificaciones>();
        }
    
        public int idNotificacion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<int> usuarioRegistro { get; set; }
        public Nullable<bool> isBeneficio { get; set; }
        public Nullable<int> beneficioId { get; set; }
        public bool activo { get; set; }
        public string titulo { get; set; }
        public int empresaId { get; set; }
        public int tipoNotificacion { get; set; }
        public Nullable<int> sucursalId { get; set; }
        public string descripcionIngles { get; set; }
        public string linea1 { get; set; }
        public string linea1ingles { get; set; }
        public string linea2 { get; set; }
        public string linea2ingles { get; set; }
        public string tituloIngles { get; set; }
        public bool notificacionAutomatica { get; set; }
    
        public virtual beneficios beneficios { get; set; }
        public virtual CatTipoNotificaciones CatTipoNotificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clienteNotificaciones> clienteNotificaciones { get; set; }
        public virtual empresas empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectoresNotificaciones> SectoresNotificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SucursalNotificaciones> SucursalNotificaciones { get; set; }
    }
}
