//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenPayTransacciones
    {
        public int idOpenPayTransaccion { get; set; }
        public int consumidorId { get; set; }
        public int catTransaccionOpenPayId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public bool estatusProceso { get; set; }
        public string datosEnvio { get; set; }
        public string datosRespuesta { get; set; }
        public Nullable<int> catCodigosErroresOpenPayId { get; set; }
        public string descripcionError { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
