//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.ConsumoEmpleados = new HashSet<ConsumoEmpleados>();
            this.PedidoProductos = new HashSet<PedidoProductos>();
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int idPedido { get; set; }
        public int aperturaId { get; set; }
        public int pedidoIdSucursal { get; set; }
        public string estatusPedido { get; set; }
        public string tipoPedido { get; set; }
        public System.DateTime fechaRegistroPedido { get; set; }
        public string usuarioRegistro { get; set; }
        public string uuidPedido { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public string mesero_numero { get; set; }
        public string mesero_nombre { get; set; }
        public string mesa_nombre { get; set; }
        public Nullable<int> catComensales { get; set; }
    
        public virtual Aperturas Aperturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumoEmpleados> ConsumoEmpleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoProductos> PedidoProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
