//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoProductoDetalle1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoProductoDetalle1()
        {
            this.InsumoProducto = new HashSet<InsumoProducto1>();
        }
    
        public int idPedidoProductoDetalle { get; set; }
        public int pedidoProductoId { get; set; }
        public int insumoProductoId { get; set; }
        public string descripcionVariedad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsumoProducto1> InsumoProducto { get; set; }
        public virtual PedidoProductos1 PedidoProductos { get; set; }
    }
}
