//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos1()
        {
            this.DetallePedidos = new HashSet<DetallePedidos>();
            this.notificaciones = new HashSet<notificaciones>();
            this.NotificacionesHazPedido = new HashSet<NotificacionesHazPedido>();
            this.PedidosConekta = new HashSet<PedidosConekta>();
            this.SeguimientoPedidos = new HashSet<SeguimientoPedidos>();
        }
    
        public int idPedido { get; set; }
        public int sucursalId { get; set; }
        public string folio { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public int catPedidoEstatusId { get; set; }
        public Nullable<decimal> costoEnvio { get; set; }
        public decimal subTotal { get; set; }
        public Nullable<decimal> totalPagar { get; set; }
        public int catMetodoPagoId { get; set; }
        public int consumidorId { get; set; }
        public Nullable<int> consumidorDireccionId { get; set; }
        public string nombreQuienRealizo { get; set; }
        public string direccionEntrega { get; set; }
        public string quienRecibe { get; set; }
        public string telefonoQuienRecibe { get; set; }
        public Nullable<int> calificacionPedido { get; set; }
        public Nullable<int> calificacionServicio { get; set; }
        public Nullable<int> calificacionAplicacion { get; set; }
        public string calificacionComentario { get; set; }
        public Nullable<bool> recogerEnSucursal { get; set; }
        public Nullable<System.DateTime> ultimaNotificacionSucursal { get; set; }
        public Nullable<decimal> comisionQDC { get; set; }
        public Nullable<decimal> comisionBanco { get; set; }
        public Nullable<bool> isCorte { get; set; }
        public string ordenOP { get; set; }
        public Nullable<bool> SolicitudPorAgente { get; set; }
        public Nullable<int> ClienteCallCenterID { get; set; }
        public int aperturaId { get; set; }
        public int pedidoIdSucursal { get; set; }
        public string estatusPedido { get; set; }
        public string tipoPedido { get; set; }
        public System.DateTime fechaRegistroPedido { get; set; }
        public string usuarioRegistro { get; set; }
        public string uuidPedido { get; set; }
        public string mesero_numero { get; set; }
        public string mesero_nombre { get; set; }
        public string mesa_nombre { get; set; }
        public Nullable<int> catComensales { get; set; }
    
        public virtual CatPedidoEstatus CatPedidoEstatus { get; set; }
        public virtual clientes clientes { get; set; }
        public virtual ClientesCallCenter ClientesCallCenter { get; set; }
        public virtual ConsumidorDirecciones ConsumidorDirecciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedidos> DetallePedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificaciones> notificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificacionesHazPedido> NotificacionesHazPedido { get; set; }
        public virtual sucursales sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosConekta> PedidosConekta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoPedidos> SeguimientoPedidos { get; set; }
        public virtual CatMetodoPago CatMetodoPago { get; set; }
        public virtual Aperturas1 Aperturas { get; set; }
    }
}
