//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoProductos()
        {
            this.InsumoProducto = new HashSet<InsumoProducto>();
            this.PedidoProductoDetalle = new HashSet<PedidoProductoDetalle>();
        }
    
        public int idPedidoProducto { get; set; }
        public int pedidoId { get; set; }
        public int productoId { get; set; }
        public decimal cantidad { get; set; }
        public int ticketId { get; set; }
        public string usuarioRegistro { get; set; }
        public string nota { get; set; }
        public bool aplicaMerma { get; set; }
        public decimal precioUnitario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsumoProducto> InsumoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoProductoDetalle> PedidoProductoDetalle { get; set; }
        public virtual Pedidos Pedidos { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
