//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosConekta
    {
        public int idPedidosConekta { get; set; }
        public string idOrdenPedido { get; set; }
        public int estatusConekta { get; set; }
        public System.DateTime fechaActualizacion { get; set; }
        public int pedidoId { get; set; }
    
        public virtual Pedidos1 Pedidos1 { get; set; }
    }
}
