//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos1()
        {
            this.AgrupadorInsumos = new HashSet<AgrupadorInsumos1>();
            this.catProductos = new HashSet<catProductos>();
            this.ConfEnsaladaPlatillos = new HashSet<ConfEnsaladaPlatillos>();
            this.ConfiguracionArmadoProductos = new HashSet<ConfiguracionArmadoProductos1>();
            this.ConfMenuPlatillosItemUno = new HashSet<ConfMenuPlatillosItemUno>();
            this.confProductoPVEquivalencia = new HashSet<confProductoPVEquivalencia>();
            this.Descuentos = new HashSet<Descuentos1>();
            this.DetallePedidos = new HashSet<DetallePedidos>();
            this.InsumoProducto = new HashSet<InsumoProducto1>();
            this.InsumoProductos = new HashSet<InsumoProductos1>();
            this.ProductoEstaConfigurado = new HashSet<ProductoEstaConfigurado>();
            this.ProductoTieneReceta = new HashSet<ProductoTieneReceta>();
            this.Recetas = new HashSet<Recetas1>();
            this.SucursalProductos = new HashSet<SucursalProductos1>();
            this.VariedadProductos = new HashSet<VariedadProductos1>();
        }
    
        public int idProducto { get; set; }
        public int comercioId { get; set; }
        public string nombre { get; set; }
        public decimal precio { get; set; }
        public bool activo { get; set; }
        public Nullable<decimal> mermaPermitida { get; set; }
        public bool esCombo { get; set; }
        public Nullable<bool> esGeneral { get; set; }
        public int usuarioRegistroId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public string clave { get; set; }
        public bool armarCobroMostrador { get; set; }
        public Nullable<int> categoriaProductoId { get; set; }
        public string urlImagen { get; set; }
        public int indice { get; set; }
        public Nullable<int> areaPreparacionId { get; set; }
        public bool principal { get; set; }
        public string urlImagenApp { get; set; }
        public string descripcion { get; set; }
        public string sku { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgrupadorInsumos1> AgrupadorInsumos { get; set; }
        public virtual AreaPreparacion1 AreaPreparacion { get; set; }
        public virtual CategoriaProductos1 CategoriaProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catProductos> catProductos { get; set; }
        public virtual comercios comercios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfEnsaladaPlatillos> ConfEnsaladaPlatillos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfiguracionArmadoProductos1> ConfiguracionArmadoProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfMenuPlatillosItemUno> ConfMenuPlatillosItemUno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<confProductoPVEquivalencia> confProductoPVEquivalencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Descuentos1> Descuentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedidos> DetallePedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsumoProducto1> InsumoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsumoProductos1> InsumoProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoEstaConfigurado> ProductoEstaConfigurado { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoTieneReceta> ProductoTieneReceta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recetas1> Recetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SucursalProductos1> SucursalProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VariedadProductos1> VariedadProductos { get; set; }
    }
}
