//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecetasProcesados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecetasProcesados()
        {
            this.DetalleRecetaProcesados = new HashSet<DetalleRecetaProcesados>();
        }
    
        public int idRecetasProcesado { get; set; }
        public int insumoId { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
        public Nullable<int> tipoRecetaId { get; set; }
        public int diasCaducidad { get; set; }
        public decimal mermaPermitida { get; set; }
        public int usuarioRegistroId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<decimal> cantidadProcesado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRecetaProcesados> DetalleRecetaProcesados { get; set; }
        public virtual Insumos Insumos { get; set; }
        public virtual TipoRecetas TipoRecetas { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
