//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class receptorCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public receptorCliente()
        {
            this.facturaCliente = new HashSet<facturaCliente>();
            this.facturaPendiente = new HashSet<facturaPendiente>();
        }
    
        public int idReceptorCliente { get; set; }
        public int clienteId { get; set; }
        public int datoReceptorId { get; set; }
        public bool prederteminada { get; set; }
        public string correo { get; set; }
        public bool estatus { get; set; }
        public string catUsoCFDId { get; set; }
    
        public virtual catUsoCFDI catUsoCFDI { get; set; }
        public virtual datosReceptor datosReceptor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaCliente> facturaCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaPendiente> facturaPendiente { get; set; }
        public virtual clientes clientes { get; set; }
    }
}
