//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class recompensas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recompensas()
        {
            this.canjePuntos = new HashSet<canjePuntos>();
        }
    
        public int idRecompesa { get; set; }
        public int productoId { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<bool> estatus { get; set; }
        public int catTipoRecompensaId { get; set; }
        public decimal valor { get; set; }
        public Nullable<int> horasCanje { get; set; }
        public Nullable<int> diasCanje { get; set; }
        public int catTipoMembresiaId { get; set; }
        public int categoriaProductoId { get; set; }
        public Nullable<decimal> consumirCanje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<canjePuntos> canjePuntos { get; set; }
        public virtual catProductos catProductos { get; set; }
        public virtual catTipoMembresias catTipoMembresias { get; set; }
        public virtual catTipoRecompensas catTipoRecompensas { get; set; }
        public virtual CategoriaProductos CategoriaProductos { get; set; }
    }
}
