//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroConteoFisicoInsumos1
    {
        public int idRegistroConteoFisicoInsumo { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> ultimaActualizacion { get; set; }
        public int sucursalId { get; set; }
        public int conteoFisicoInsumoId { get; set; }
        public int conteoFisicoAgrupadorInsumosId { get; set; }
        public Nullable<int> usuarioActualizaId { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string descripcionUnidadMedida { get; set; }
        public int conteoFisicoTipoRegistroId { get; set; }
    
        public virtual ConteoFisicoAgrupadorInsumos1 ConteoFisicoAgrupadorInsumos { get; set; }
        public virtual ConteoFisicoInsumos1 ConteoFisicoInsumos { get; set; }
        public virtual ConteoFisicoTipoRegistro1 ConteoFisicoTipoRegistro { get; set; }
        public virtual sucursales sucursales { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
