//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoBitacoraPedidos
    {
        public int idSeguimientoBitacoraPedido { get; set; }
        public int seguimientoPedidoId { get; set; }
        public string comentario { get; set; }
        public bool isconsumidor { get; set; }
        public int usuarioIdRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    
        public virtual SeguimientoPedidos SeguimientoPedidos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
