//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoPedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeguimientoPedidos()
        {
            this.SeguimientoBitacoraPedidos = new HashSet<SeguimientoBitacoraPedidos>();
        }
    
        public int idSeguimientoPedido { get; set; }
        public int pedidoId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int catPedidoEstatusId { get; set; }
        public string nombreRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoBitacoraPedidos> SeguimientoBitacoraPedidos { get; set; }
        public virtual CatPedidoEstatus CatPedidoEstatus { get; set; }
        public virtual Pedidos1 Pedidos1 { get; set; }
        public virtual Pedidos11 Pedidos11 { get; set; }
    }
}
