//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursalHorarios
    {
        public int idSucursalHorario { get; set; }
        public int sucursalId { get; set; }
        public string diasNum { get; set; }
        public string horarioInicio { get; set; }
        public string horarioFin { get; set; }
        public string descripcion { get; set; }
        public int dayOfWeek { get; set; }
    
        public virtual sucursales sucursales { get; set; }
    }
}
