//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucursalDescuentos
    {
        public int idSucursalDescuento { get; set; }
        public int descuentoId { get; set; }
        public int sucursalId { get; set; }
        public bool activo { get; set; }
        public int usuarioRegistroId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual sucursales sucursales { get; set; }
        public virtual Descuentos Descuentos { get; set; }
    }
}
