//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucursalNotificaciones
    {
        public int idSucursalNotificacion { get; set; }
        public int notificacionId { get; set; }
        public int sucursalId { get; set; }
    
        public virtual notificaciones notificaciones { get; set; }
    }
}
