//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucursalCategoriaProducto1
    {
        public int IdSucursalCategoriaProducto { get; set; }
        public int SucursalID { get; set; }
        public int CategoriaProductoID { get; set; }
        public bool Activo { get; set; }
        public int UsuarioRegistroID { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual CategoriaProductos1 CategoriaProductos { get; set; }
        public virtual sucursales sucursales { get; set; }
    }
}
