//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sucursales()
        {
            this.Arqueo = new HashSet<Arqueo>();
            this.Inventarios = new HashSet<Inventarios>();
            this.MobiliarioEquipos = new HashSet<MobiliarioEquipos>();
            this.RegistroConteoFisicoInsumos = new HashSet<RegistroConteoFisicoInsumos>();
            this.SucursalDescuentos = new HashSet<SucursalDescuentos>();
            this.SucursalProductos = new HashSet<SucursalProductos>();
            this.SucursalProveedores = new HashSet<SucursalProveedores>();
            this.Ventas = new HashSet<Ventas>();
            this.beneficioAplicados = new HashSet<beneficioAplicados>();
            this.canjePuntos = new HashSet<canjePuntos>();
            this.cargaCompras = new HashSet<cargaCompras>();
            this.confBeneficioSucursal = new HashSet<confBeneficioSucursal>();
            this.confDatosFiscalesSucursal = new HashSet<confDatosFiscalesSucursal>();
            this.ConfUsuarioSucursales = new HashSet<ConfUsuarioSucursales>();
            this.facturaPendiente = new HashSet<facturaPendiente>();
            this.movimientoPuntos = new HashSet<movimientoPuntos>();
            this.sucursalHorarios = new HashSet<sucursalHorarios>();
            this.MovimientoInventarios = new HashSet<MovimientoInventarios>();
            this.Compras = new HashSet<Compras>();
            this.Gastos = new HashSet<Gastos>();
            this.GastosPvDetalle = new HashSet<GastosPvDetalle>();
            this.Citas = new HashSet<Citas>();
            this.Menus = new HashSet<Menus>();
            this.Platillos = new HashSet<Platillos>();
            this.ItemDos = new HashSet<ItemDos>();
            this.ItemTres = new HashSet<ItemTres>();
            this.ItemUno = new HashSet<ItemUno>();
            this.ConfSucursales = new HashSet<ConfSucursales>();
            this.BitacoraSucursalesActivas = new HashSet<BitacoraSucursalesActivas>();
            this.NotificacionesHazPedido = new HashSet<NotificacionesHazPedido>();
            this.SucursalCategoriaProducto = new HashSet<SucursalCategoriaProducto>();
            this.ConfMenuPlatillosItemUno = new HashSet<ConfMenuPlatillosItemUno>();
            this.ConfUsuariosComercioSucursal = new HashSet<ConfUsuariosComercioSucursal>();
            this.Pedidos1 = new HashSet<Pedidos1>();
        }
    
        public int idSucursal { get; set; }
        public int comercioId { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public int direccionId { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string placeId { get; set; }
        public int usuarioRegistroId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public bool activo { get; set; }
        public Nullable<int> radioZonaMystique { get; set; }
        public Nullable<int> sucursalPuntoVenta { get; set; }
        public Nullable<int> usuarioActualizoId { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
        public Nullable<int> datosFiscalesId { get; set; }
        public Nullable<decimal> maxEfectivo { get; set; }
        public Nullable<decimal> costoEnvio { get; set; }
        public string faceBook { get; set; }
        public string sitioWeb { get; set; }
        public string mensajeTicket { get; set; }
        public Nullable<decimal> iva { get; set; }
        public string logoTickets { get; set; }
        public Nullable<int> catZonaId { get; set; }
        public string twitter { get; set; }
        public string instagram { get; set; }
        public string colorIndicador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arqueo> Arqueo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventarios> Inventarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobiliarioEquipos> MobiliarioEquipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroConteoFisicoInsumos> RegistroConteoFisicoInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SucursalDescuentos> SucursalDescuentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SucursalProductos> SucursalProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SucursalProveedores> SucursalProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<beneficioAplicados> beneficioAplicados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<canjePuntos> canjePuntos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cargaCompras> cargaCompras { get; set; }
        public virtual CatZonas CatZonas { get; set; }
        public virtual comercios comercios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<confBeneficioSucursal> confBeneficioSucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<confDatosFiscalesSucursal> confDatosFiscalesSucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfUsuarioSucursales> ConfUsuarioSucursales { get; set; }
        public virtual datosFiscales datosFiscales { get; set; }
        public virtual direccion direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaPendiente> facturaPendiente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientoPuntos> movimientoPuntos { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sucursalHorarios> sucursalHorarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoInventarios> MovimientoInventarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras> Compras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gastos> Gastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastosPvDetalle> GastosPvDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menus> Menus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platillos> Platillos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemDos> ItemDos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemTres> ItemTres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemUno> ItemUno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfSucursales> ConfSucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraSucursalesActivas> BitacoraSucursalesActivas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificacionesHazPedido> NotificacionesHazPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SucursalCategoriaProducto> SucursalCategoriaProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfMenuPlatillosItemUno> ConfMenuPlatillosItemUno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfUsuariosComercioSucursal> ConfUsuariosComercioSucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos1> Pedidos1 { get; set; }
    }
}
