//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketPagos1
    {
        public int idTicketPago { get; set; }
        public string tipoPago { get; set; }
        public int ticketId { get; set; }
        public decimal importe { get; set; }
        public string confirmacion { get; set; }
        public string banco { get; set; }
        public Nullable<int> tipoPagoId { get; set; }
        public decimal importeOriginal { get; set; }
    
        public virtual CatTipoPagos1 CatTipoPagos { get; set; }
        public virtual Tickets1 Tickets { get; set; }
    }
}
