//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketSucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ticketSucursal()
        {
            this.detalleTicketSucursal = new HashSet<detalleTicketSucursal>();
            this.facturaCliente = new HashSet<facturaCliente>();
            this.trasladosImpuestosTicket = new HashSet<trasladosImpuestosTicket>();
        }
    
        public string idTicketSucursal { get; set; }
        public string folio { get; set; }
        public int sucursalId { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public decimal subtotal { get; set; }
        public decimal iva { get; set; }
        public decimal descuento { get; set; }
        public decimal total { get; set; }
        public int claveMetodoPago { get; set; }
        public int claveFormaPago { get; set; }
        public int claveTipoComprobante { get; set; }
        public int catEstatusTicketId { get; set; }
        public string referencia { get; set; }
        public string lugarExpedicionFactura { get; set; }
        public string serieFactura { get; set; }
        public string folioFactura { get; set; }
        public string condicionesPago { get; set; }
        public int moneda { get; set; }
        public decimal tipoCambio { get; set; }
    
        public virtual catEstatusTicket catEstatusTicket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleTicketSucursal> detalleTicketSucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaCliente> facturaCliente { get; set; }
        public virtual sucursales sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trasladosImpuestosTicket> trasladosImpuestosTicket { get; set; }
    }
}
