//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransaccionesConekta
    {
        public int idTransaccionesConekta { get; set; }
        public string transaccion { get; set; }
        public string entrada { get; set; }
        public string salida { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    }
}
