//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class trasladosImpuestosTicket
    {
        public int idTrasladosImpuestosTicket { get; set; }
        public string idTicketSucursal { get; set; }
        public decimal tasaImpuestos { get; set; }
        public decimal impuesto { get; set; }
        public int claveImpuesto { get; set; }
    
        public virtual ticketSucursal ticketSucursal { get; set; }
    }
}
