//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariedadProductos
    {
        public int idVariedadProducto { get; set; }
        public int productoId { get; set; }
        public string descripcion { get; set; }
        public string imagen { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
