//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ObtenerClientesConMembresia
    {
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public int IdMembresia { get; set; }
        public string NombreCompleto { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Colonia { get; set; }
        public string Ciudad { get; set; }
        public string Sexo { get; set; }
        public decimal PuntosActuales { get; set; }
        public decimal SumaCompras { get; set; }
        public decimal SumaCanjeados { get; set; }
        public Nullable<int> BeneficiosAplicados { get; set; }
    }
}
