//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ObtenerRecompensasPorProductos
    {
        public int comercioId { get; set; }
        public int idRecompesa { get; set; }
        public string descripcion { get; set; }
        public decimal valor { get; set; }
        public Nullable<int> diasCanje { get; set; }
        public int catTipoMembresiaId { get; set; }
        public int catTipoRecompensaId { get; set; }
        public Nullable<bool> estatus { get; set; }
        public string imagen { get; set; }
        public string descripcionProducto { get; set; }
        public int idCatProducto { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
    }
}
