//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ObtenerListadoCupones
    {
        public int comercioId { get; set; }
        public int idCanjePunto { get; set; }
        public int membresiaId { get; set; }
        public int recompensaId { get; set; }
        public int productoId { get; set; }
        public string descripcion { get; set; }
        public string imagen { get; set; }
        public int catEstatusCanjePuntoId { get; set; }
        public string estatusCanje { get; set; }
        public int productoPuntoVentaId { get; set; }
        public string folioCanje { get; set; }
        public Nullable<System.DateTime> fechaFinCanje { get; set; }
        public string diasRestantes { get; set; }
        public string horasRestantes { get; set; }
        public string minutosRestantes { get; set; }
    }
}
