//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Permisos
    {
        public int idUsuario { get; set; }
        public string controlador { get; set; }
        public string accion { get; set; }
        public string nombreRol { get; set; }
        public string aspNetUserId { get; set; }
        public string aspNetRoleId { get; set; }
    }
}
