//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PV_Listado_Ventas
    {
        public int idApertura { get; set; }
        public int aperturaIdSucursal { get; set; }
        public int sucursalId { get; set; }
        public System.DateTime fechaRegistroApertura { get; set; }
        public System.DateTime fechaInicial { get; set; }
        public System.DateTime fechaFinal { get; set; }
        public int pedidoId { get; set; }
        public int ticketIdSucursal { get; set; }
        public bool facturado { get; set; }
        public decimal subtotal { get; set; }
        public decimal iva { get; set; }
        public decimal importe { get; set; }
        public Nullable<System.DateTime> fechaCancelacion { get; set; }
        public string tipoPago { get; set; }
        public decimal ImporteTipoPago { get; set; }
        public string banco { get; set; }
        public string usuarioConsume { get; set; }
        public int idVenta { get; set; }
        public System.DateTime fechaCobro { get; set; }
        public Nullable<int> tipoPagoId { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> aplicaCxc { get; set; }
        public bool estaCancelado { get; set; }
        public decimal importeOriginal { get; set; }
    }
}
