//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PV_Ticket_Pedido_Productos1
    {
        public int idTicket { get; set; }
        public int numeroTicket { get; set; }
        public string folioTicket { get; set; }
        public System.DateTime fechaCobro { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int productoId { get; set; }
        public decimal cantidad { get; set; }
        public decimal precioUnitario { get; set; }
        public int idCategoriaProducto { get; set; }
        public int sucursalId { get; set; }
        public decimal precio { get; set; }
        public bool estaCancelado { get; set; }
        public bool activo { get; set; }
    }
}
