//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_REPORTE_MACHOTE
    {
        public int idApertura { get; set; }
        public int idTicket { get; set; }
        public string Folio { get; set; }
        public System.DateTime Fecha { get; set; }
        public string UsuarioRegistro { get; set; }
        public string TipoPedido { get; set; }
        public string TipoPago { get; set; }
        public decimal TipoPagoImporte { get; set; }
        public decimal ImporteTotalTicket { get; set; }
        public string Familia { get; set; }
        public string Producto { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> ImporteTotalProducto { get; set; }
    }
}
