//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MystiqueMC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wallet
    {
        public int idWallet { get; set; }
        public int beneficioId { get; set; }
        public int clienteId { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public bool estatus { get; set; }
    
        public virtual beneficios beneficios { get; set; }
        public virtual clientes clientes { get; set; }
    }
}
